#!/bin/bash
##
## EPITECH PROJECT, 2021
## my_scripts - change_branch
## File description:
## jitter jitter
##

if [ $# -eq 1 ]
then
    if [ $1 == "-h" ] || [ $1 == "-H" ] || [ $1 == "--help" ] || [ $1 == "--HELP"]
    then
        echo "Change branches"
        echo "Call $0 <branch_name> to run the command"
    else
        echo "switching branches"
        git fetch
        git switch -c "$1"
        git switch "$1"
        git branch -u="$1"
        echo "git status"
        git status
        echo "listing exisitng branches in the git"
        list_all_branches
    fi
else
    echo "Please enter the branche you wish to create."
    echo "Syntax: $0 <branch_name>"
fi
echo "(c) Created by Henry Letellier"
