#!/bin/bash
##
## EPITECH PROJECT, 2021
## my_scripts
## File description:
## force_delete_branch
##

if [ $# -eq 1 ]
then
    if [ $1 == "-h" ] || [ $1 == "-H" ] || [ $1 == "--help" ] || [ $1 == "--HELP"]
    then
        echo "Force delete a branch"
        echo "Call $0 <branch_name> to run the command"
    else
        git branch -r -D "$1"
    fi
else
    echo "Please enter the branche you wish to force delete."
    echo "Syntax: $0 <branch_name>"
fi
echo "(c) Created by Henry Letellier"
