#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## my_scripts - colors (main menu)
## File description:
## jitter jitter
##

def get_first_letters(string:str) -> list[str,str]:
    """ get the first letter of each word """
    letters = ""
    letters_with_underscore = ""
    letters_with_underscore_cleaned = ""
    string_list = string.split('_')
    list_length = len(string_list)
    for i in range(list_length):
        if (string_list[i][0] != '"' and string_list[i][0] != "'"):
            letters+=string_list[i][0]
            letters_with_underscore+=string_list[i][0]
        else:
            letters+=string_list[i][1]
            letters_with_underscore+=string_list[i][1]
        letters_with_underscore+="_"
    for i in range(len(letters_with_underscore)-1):
        letters_with_underscore_cleaned+=letters_with_underscore[i]
    return [letters, letters_with_underscore_cleaned]

def get_two_first_letters(string:str) -> list[str, str]:
    """ Get the two first letters of each word """
    letters = ""
    letters_with_underscore = ""
    letters_with_underscore_cleaned = ""
    string_list = string.split('_')
    list_length = len(string_list)
    for i in range(list_length):
        if (string_list[i][0] != '"' and string_list[i][0] != "'"):
            letters+=string_list[i][0]
            letters_with_underscore+=string_list[i][0]
            if (len(string_list[i]) > 1):
                letters+=string_list[i][1]
                letters_with_underscore+=string_list[i][1]
        else:
            letters+=string_list[i][1]
            letters_with_underscore+=string_list[i][1]
            if (len(string_list[i]) > 2):
                letters+=string_list[i][2]
                letters_with_underscore+=string_list[i][2]
        letters_with_underscore+="_"
    for i in range(len(letters_with_underscore)-1):
        letters_with_underscore_cleaned+=letters_with_underscore[i]
    return [letters, letters_with_underscore_cleaned]

a = input("Enter commands to trim:")
var_name = input("Enter the name of the variable:")
a=a.split('\\n')
for i in range(len(a)):
    if (a[i] != ''):
        print(f"{var_name}[\"{a[i]}\"]=\"{a[i]}\"")
        temp = get_first_letters(a[i])
        print(f"{var_name}[\"{temp[0]}\"]=\"{a[i]}\"")
        print(f"{var_name}[\"{temp[1]}\"]=\"{a[i]}\"")
        temp = get_two_first_letters(a[i])
        print(f"{var_name}[\"{temp[0]}\"]=\"{a[i]}\"")
        print(f"{var_name}[\"{temp[1]}\"]=\"{a[i]}\"")
